//! Build-time generator for the `inspect help --search` index.
//!
//! HP-3 (see `INSPECT_HELP_IMPLEMENTATION_PLAN.md` §HP-3).
//!
//! Reads two corpora and emits a single Rust source file at
//! `$OUT_DIR/help_index.rs` that `src/help/search.rs` includes via
//! `include!`. Pure `std` — no extra runtime or build-time deps.
//!
//! Corpora:
//!   1. Every `src/help/content/*.md` topic body. Topic id = file stem.
//!   2. Every `pub const LONG_<NAME>: &str = "...";` literal in
//!      `src/cli.rs`. Topic id = `cmd:<name>` (lower-cased), so a
//!      search for "timeout" surfaces `cmd:grep`, `cmd:edit`,
//!      `cmd:search`, … alongside the prose topics — this is what the
//!      bible means by "every topic, verb, flag, and example".
//!
//! Emitted shape:
//!   pub static TOPIC_IDS:   &[&str]                       = &[..];
//!   pub static TOPIC_LINES: &[&[&str]]                    = &[..];
//!   pub static KEYWORDS:    &[(&str, &[(u16, u32)])]      = &[..];
//!
//! `KEYWORDS` is sorted by keyword. Each tuple `(topic_idx, line_idx)`
//! is 0-indexed; the runtime renders `line_idx + 1` for human output.

use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::fs;
use std::io::Write;
use std::path::PathBuf;

/// Common English noise. Per plan §HP-3: "strip 30-word stop list".
/// Deliberately small — over-aggressive stopping silently breaks
/// interactive searches like `inspect help --search "is enabled"`.
const STOPWORDS: &[&str] = &[
    "the", "a", "an", "and", "or", "but", "of", "to", "in", "on",
    "at", "for", "with", "by", "from", "as", "is", "are", "was", "were",
    "be", "been", "this", "that", "it", "its", "has", "have", "had", "not",
];

fn main() {
    println!("cargo:rerun-if-changed=src/help/content");
    println!("cargo:rerun-if-changed=src/cli.rs");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let dest = PathBuf::from(&out_dir).join("help_index.rs");

    // (topic_id, lines)
    let mut topics: Vec<(String, Vec<String>)> = Vec::new();

    // 1. Markdown topics — sorted by filename for deterministic output.
    let content_dir = PathBuf::from("src/help/content");
    let mut md: Vec<PathBuf> = fs::read_dir(&content_dir)
        .expect("read src/help/content")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("md"))
        .collect();
    md.sort();
    for path in md {
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("md filename")
            .to_string();
        let body = fs::read_to_string(&path).expect("read md file");
        let lines: Vec<String> = body.lines().map(|s| s.to_string()).collect();
        topics.push((stem, lines));
    }

    // 2. cli.rs LONG_* literals — synthetic `cmd:<verb>` topics.
    let cli_src = fs::read_to_string("src/cli.rs").expect("read src/cli.rs");
    let long_consts = extract_long_consts(&cli_src);
    for (name, body) in long_consts {
        let id = format!("cmd:{}", name.to_ascii_lowercase());
        let lines: Vec<String> = body.lines().map(|s| s.to_string()).collect();
        topics.push((id, lines));
    }

    // 3. Inverted index.
    let stop: HashSet<&str> = STOPWORDS.iter().copied().collect();
    let mut index: BTreeMap<String, BTreeSet<(u16, u32)>> = BTreeMap::new();
    for (ti, (_id, lines)) in topics.iter().enumerate() {
        let ti_u16 = u16::try_from(ti).expect("≤ 65535 topics");
        for (li, line) in lines.iter().enumerate() {
            let li_u32 = u32::try_from(li).expect("≤ 4 billion lines/topic");
            for tok in tokenize(line) {
                if tok.len() < 2 || stop.contains(tok.as_str()) {
                    continue;
                }
                index.entry(tok).or_default().insert((ti_u16, li_u32));
            }
        }
    }

    // 4. Emit.
    let mut f = fs::File::create(&dest).expect("create help_index.rs");
    writeln!(f, "// AUTO-GENERATED by build.rs — HP-3 search index. Do not edit.").unwrap();
    writeln!(f).unwrap();

    writeln!(f, "pub static TOPIC_IDS: &[&str] = &[").unwrap();
    for (id, _) in &topics {
        writeln!(f, "    {},", rust_str(id)).unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();

    writeln!(f, "pub static TOPIC_LINES: &[&[&str]] = &[").unwrap();
    for (_, lines) in &topics {
        writeln!(f, "    &[").unwrap();
        for line in lines {
            writeln!(f, "        {},", rust_str(line)).unwrap();
        }
        writeln!(f, "    ],").unwrap();
    }
    writeln!(f, "];").unwrap();
    writeln!(f).unwrap();

    writeln!(f, "pub static KEYWORDS: &[(&str, &[(u16, u32)])] = &[").unwrap();
    for (kw, locs) in &index {
        write!(f, "    ({}, &[", rust_str(kw)).unwrap();
        for (ti, li) in locs {
            write!(f, "({},{}),", ti, li).unwrap();
        }
        writeln!(f, "]),").unwrap();
    }
    writeln!(f, "];").unwrap();
}

/// Lossless ASCII-friendly Rust string literal. We deliberately avoid
/// `{:?}` because `Debug` for `String` does not guarantee a stable
/// escape policy; the test suite snapshots the generated file's
/// shape and we want byte-stable output across rustc versions.
fn rust_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                out.push_str(&format!("\\u{{{:x}}}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Tokenize a line into lowercase alphanumeric words. `_` and `-`
/// are kept inside tokens so identifiers like `dry-run` survive.
fn tokenize(line: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    for c in line.chars() {
        if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
            for lc in c.to_lowercase() {
                cur.push(lc);
            }
        } else if !cur.is_empty() {
            out.push(std::mem::take(&mut cur));
        }
    }
    if !cur.is_empty() {
        out.push(cur);
    }
    out
}

/// Extract every `pub? const LONG_<NAME>: &str = "<body>";` literal
/// from `src/cli.rs`. Handles the four escape sequences we actually
/// use in those literals: `\\`, `\"`, `\n`, and the `\<newline>`
/// line-continuation that strips the newline plus leading whitespace
/// (the standard Rust string-literal rule).
fn extract_long_consts(src: &str) -> Vec<(String, String)> {
    let needle = "const LONG_";
    let bytes = src.as_bytes();
    let mut out = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        let Some(rel) = src[i..].find(needle) else {
            break;
        };
        let start = i + rel + needle.len();
        // Read NAME (uppercase / underscore / digit).
        let mut j = start;
        while j < bytes.len()
            && (bytes[j].is_ascii_uppercase() || bytes[j] == b'_' || bytes[j].is_ascii_digit())
        {
            j += 1;
        }
        let name = src[start..j].to_string();
        // Find the opening quote of the literal value.
        let Some(qrel) = src[j..].find('"') else {
            break;
        };
        let mut k = j + qrel + 1;
        let mut body = String::new();
        let mut closed = false;
        while k < bytes.len() {
            let c = bytes[k];
            if c == b'\\' && k + 1 < bytes.len() {
                let n = bytes[k + 1];
                match n {
                    b'\n' => {
                        // Line continuation: drop \n + following whitespace.
                        k += 2;
                        while k < bytes.len()
                            && (bytes[k] == b' ' || bytes[k] == b'\t')
                        {
                            k += 1;
                        }
                        continue;
                    }
                    b'n' => body.push('\n'),
                    b't' => body.push('\t'),
                    b'r' => body.push('\r'),
                    b'\\' => body.push('\\'),
                    b'"' => body.push('"'),
                    b'\'' => body.push('\''),
                    other => body.push(other as char),
                }
                k += 2;
            } else if c == b'"' {
                closed = true;
                i = k + 1;
                break;
            } else {
                body.push(c as char);
                k += 1;
            }
        }
        if !closed {
            // Malformed (or we ran off the end); skip this hit.
            i = j + 1;
            continue;
        }
        out.push((name, body));
    }
    out
}
